version: '3'

volumes:
  uniquiz_local_postgres_data: {}
  uniquiz_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: uniquiz_local_django
    container_name: uniquiz_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
    networks:
      bridge:
        aliases:
          - uniquiz_local_django

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: uniquiz_production_postgres
    container_name: uniquiz_local_postgres
    volumes:
      - uniquiz_local_postgres_data:/var/lib/postgresql/data
      - uniquiz_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      bridge:
        aliases:
          - postgres
  uniquiz_react_app:
    build:
      context: .
      dockerfile: ./compose/local/react/Dockerfile
    volumes:
      - ./react_app/src:/user/src/react_app/src:z
    ports:
      - 3000:3000
    networks:
      bridge:
        aliases:
          - uniquiz_react_app

  uniquiz_nginx:
    image: nginx:1.15
    container_name: uniquiz_nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:rw
      - ./static_django:/etc/nginx/static_django
    ports:
      - 80:80
    networks:
      - bridge
    depends_on:
      - uniquiz_react_app

  docs:
    image: uniquiz_local_docs
    container_name: uniquiz_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./uniquiz:/app/uniquiz:z
    ports:
      - '9000:9000'
    command: /start-docs
networks:
  bridge:
