version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: uniquiz_production_django
    volumes:
      - production_django_media:/app/uniquiz/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      bridge:
        aliases:
          - uniquiz_production_django

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: uniquiz_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      bridge:
        aliases:
          - postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: uniquiz_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    networks:
      bridge:
        aliases:
          - uniquiz_production_traefik

  redis:
    image: redis:6

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: uniquiz_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    networks:
      bridge:
        aliases:
          - uniquiz_production_nginx

  react:
    build:
      context: .
      dockerfile: ./compose/production/react/Dockerfile
    image: uniquiz_production_react
    depends_on:
      - django
    volumes:
      - ./react_app/src:/user/src/react_app/src
    ports:
      - 3000:3000
    networks:
      bridge:
        aliases:
          - uniquiz_production_react
  
networks:
  bridge:
