# Generated by Django 4.2.4 on 2023-09-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
