# Generated by Django 4.2.4 on 2023-09-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_alter_quiz_end_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="current_question",
            field=models.IntegerField(default=1),
        ),
    ]
