# Generated by Django 4.2.4 on 2023-09-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_quiz_current_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
