# Generated by Django 4.2.4 on 2023-09-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_quiz_total_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="total_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
